export const CREATE_TODO_REQUEST = "CREATE_TODO_REQUEST";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAIL = "CREATE_TODO_FAIL";

export const MY_TODOS_REQUEST = "MY_TODOS_REQUEST";
export const MY_TODOS_SUCCESS = "MY_TODOS_SUCCESS";
export const MY_TODOS_FAIL = "MY_TODOS_FAIL";

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL";


export const DONE_TODO_REQUEST = "DONE_TODO_REQUEST";
export const DONE_TODO_SUCCESS = "DONE_TODO_SUCCESS";
export const DONE_TODO_FAIL = "DONE_TODO_FAIL";

export const UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FAIL = "UPDATE_TODO_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";